# Generated by Django 5.2.2 on 2025-06-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='desc',
            field=models.TextField(verbose_name='Описание отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название отдела'),
        ),
    ]
