# Generated by Django 5.2.2 on 2025-06-09 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headed_department', related_query_name='headed_department', to='employees.employee', verbose_name='Руководитель отдела'),
        ),
    ]
