# Generated by Django 5.2.2 on 2025-06-09 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('contact', models.CharField(max_length=100, verbose_name='Контактные данные')),
                ('rate', models.CharField(choices=[('1', 'Полная'), ('0.75', '0,75'), ('0.5', '0,5'), ('0.25', '0,25')], default='full', max_length=100, verbose_name='Ставка')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата трудоустройства')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Отдел')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
