# Generated by Django 5.2.2 on 2025-06-08 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_alter_department_created_at_alter_department_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('contact', models.CharField(max_length=100, verbose_name='Контактные данные')),
                ('rate', models.CharField(choices=[('full', 'Полная'), ('0.5', '0,5'), ('0.25', '0,25'), ('0.75', '0,75')], default='full', max_length=100, verbose_name='Ставка')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
