# Generated by Django 5.2.2 on 2025-06-08 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Приема на работу'),
        ),
    ]
