# Generated by Django 5.2.2 on 2025-06-08 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_created_at_employee_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата Приема на работу'),
        ),
    ]
