# Generated by Django 5.2.2 on 2025-06-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('main', 'Основной персонал'), ('seasonal', 'Сезонный'), ('partTime', 'Совместитель')], default='main', max_length=100, verbose_name='Статус сотрудника'),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.CharField(choices=[('1', 'Полная'), ('0.75', '0,75'), ('0.5', '0,5'), ('0.25', '0,25')], default='full', max_length=100, verbose_name='Ставка'),
        ),
    ]
